# Generated by Django 2.1.3 on 2018-11-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='desc',
            field=models.CharField(default='default desc', max_length=500),
            preserve_default=False,
        ),
    ]
