# Generated by Django 2.1.3 on 2018-11-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_auto_20181121_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='path',
        ),
        migrations.AddField(
            model_name='challenge',
            name='file',
            field=models.FileField(default='test', upload_to='challenges'),
            preserve_default=False,
        ),
    ]
