# Generated by Django 2.1.3 on 2018-12-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0005_auto_20181121_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='file',
        ),
        migrations.AddField(
            model_name='challenge',
            name='desc',
            field=models.CharField(default='Default desc', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challenge',
            name='has_input',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challenge',
            name='has_output',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challenge',
            name='validate_text',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='challenge',
            name='validation_format',
            field=models.CharField(default='Todo set validation text', max_length=200),
            preserve_default=False,
        ),
    ]
