# Generated by Django 2.1.3 on 2018-12-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0007_auto_20181203_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='level',
            field=models.CharField(max_length=100),
        ),
    ]
