# Generated by Django 2.1.3 on 2019-03-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0011_remove_challenge_has_indent'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='has_indent',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
